<?php

class PopulateCommand extends CConsoleCommand
{
	
	const BLOGS_COUNT = 100;
	const COMMENTS_COUNT = 15;
	
	public $verbose=true;
	
	public function actionPopulate($args)
	{
		$post = new Post();
		$post->title = "This is YET ANOTHER auto-generated post";
		$post->content = "This is dummy content for the autogenerated post";
		$post->status = Post::STATUS_PUBLISHED;
		$post->tags = "foo,bar,comment";
		
		$post->save();
		
		$comment = new Comment();
		$comment->author = "Mike";
		$comment->email = "test@example.com";
		$comment->url = "http://www.yahoo.com";
		$comment->content = "This is an auto-generated comment";
		
		$post->addComment($comment);
		
	}
	
}